### ISSUE TITLE
执行bash job_evaluate_val.sh出现 from .__ext import lib as _lib, ffi as _ffi问题

### ISSUE THREAD

**Issue by wertjy** [31sy/PGECNet#2]
环境pytorch0.4.1,cuda9.0
执行bash job_evaluate_val.sh，出现File "/home/PGECNet-master/PGECNet-master/modules/_ext/__init__.py", line 3, in <module>
  from .__ext import lib as _lib, ffi as _ffi

**Comment by 31sy** [comment]
Do you run the code to build the modules?
cd modules
sh build.sh
python build.py
The inplace_abn in modules should be compiled accurately first.

**Comment by 31sy** [comment]
This issue will be closed.
